Default: &defaults
  host: ""
  port: 3000
  copyright: Insert copyright statement here
  #analytics: UA-YOURCODE

Development:
  <<: *defaults

Testing:
  <<: *defaults
  port: 2999

Staging:
  <<: *defaults

Production:
  approot: "http://www.example.com"
  <<: *defaults
