Default: &defaults
  host: "*4" # any IPv4 host
  port: 3000
  approot: "http://localhost:3000"
  copyright: Insert copyright statement here
  auth: false
  #analytics: UA-YOURCODE

Development:
  <<: *defaults
  approot: "/wandbox/test"

Testing:
  <<: *defaults

Staging:
  <<: *defaults

Production:
  <<: *defaults
  approot: "http://melpon.org/wandbox"
  port: 3100
