Default: &defaults
  approot: "/wandbox/test"
  port: 3000
  auth: true
  copyright: Insert copyright statement here
  #analytics: UA-YOURCODE

Development:
  <<: *defaults

Localhost:
  approot: "localhost"
  port: 8080
  auth: false
  <<: *defaults

Production:
  approot: "http://melpon.org/wandbox"
  port: 3100
  <<: *defaults
