Default: &defaults
  host: ""
  port: 3000
  copyright: Insert copyright statement here
  #analytics: UA-YOURCODE

Development:
  <<: *defaults

Testing:
  approot: "http://49.212.124.83:8080"
  port: 8080
  <<: *defaults

Staging:
  <<: *defaults

Production:
  approot: "http://49.212.124.83"
  port: 80
  <<: *defaults
