Default: &defaults
  approot: "/wandbox/test"
  port: 3000
  copyright: Insert copyright statement here
  #analytics: UA-YOURCODE

Development:
  <<: *defaults

Testing:
  <<: *defaults

Staging:
  <<: *defaults

Production:
  approot: "http://melpon.org/wandbox"
  port: 3100
  <<: *defaults
