Default: &defaults
  approot: "/wandbox/test"
  port: 3000
  auth: false
  session_key: "config/client_session_key.aes"
  sqlite_setting: "config/sqlite.yml"
  copyright: Insert copyright statement here
  compiler_config: "../cattleshed/config"
  #analytics: UA-YOURCODE

Development:
  <<: *defaults

Localhost:
  <<: *defaults
  approot: "localhost"
  port: 8080

Production:
  <<: *defaults
  approot: "http://melpon.org/wandbox"
  port: 3100
