Default: &defaults
  approot: "/wandbox/test"
  port: 3000
  auth: true
  session_key: "config/client_session_key.aes"
  sqlite_setting: "config/sqlite.yml"
  static_dir: "static"
  static_temp_dir: "static"
  copyright: Insert copyright statement here
  #analytics: UA-YOURCODE

Development:
  <<: *defaults

Localhost:
  <<: *defaults
  approot: "localhost"
  port: 8080
  auth: false

Production:
  <<: *defaults
  approot: "http://melpon.org/wandbox"
  port: 3100
