Default: &defaults
  database: kennel.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Localhost:
  database: kennel_localhost.sqlite3
  <<: *defaults

Production:
  database: "/usr/local/wandbox/kennel/kennel_production.sqlite3"
  poolsize: 100
  <<: *defaults
