Default: &defaults
  database: kennel.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: kennel_test.sqlite3
  <<: *defaults

Staging:
  database: kennel_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: kennel_production.sqlite3
  poolsize: 100
  <<: *defaults
