Default: &defaults
  database: kennel.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Localhost:
  <<: *defaults
  database: kennel_localhost.sqlite3

Production:
  <<: *defaults
  database: "kennel_production.sqlite3"
  poolsize: 100
